runtime: python39  # atau runtime lain yang sesuai

env: standard

handlers:
  # Menangani favicon
  - url: /favicon\.png
    static_files: favicon.png
    upload: favicon\.png

  # Menangani folder gambar
  - url: /src/images
    static_dir: src/images/

  # Menangani folder styles
  - url: /src/styles
    static_dir: src/styles/

  # Menangani folder scripts
  - url: /src/scripts
    static_dir: src/scripts/

  # Menangani file index.html
  - url: /
    static_files: index.html
    upload: index.html
